((magit-branch nil)
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-log
  ("-n256" "--graph" "--decorate"))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-reset nil)
 (magit-stash nil))
